### ISSUE TITLE
Allow limiting find() to a range to search within?

### ISSUE THREAD

**Issue by idupree** [dwachss/bililiteRange#13]
I wrote a patch to do this at https://github.com/idupree/bililiteRange/commit/2ffbce58f44d6f65d177e42c7b69eb80f95c0e38 while working on other things about find().  However, I'm not sure about this API and I haven't tested it much.  So I'm opening this "issue" to discuss if you're interested in the change and/or have opinions about the API design.

An example use: This could be used to implement a "find within current paragraph" functionality if someone wanted to only search a paragraph rather than a whole file for some reason.

(Was this explanation clear, or should I try again?)

**Comment by dwachss** [comment]
I think a better API would limit the find to the current range, rather than find/findback which start from the current range and cover the entire element. Something like 
```
findWithin: function(re){
  return this.findprimitive(re, this.bounds());
}
```
Would this not work?

**Comment by dwachss** [comment]
I haven't had time to work on this and it doesn't look like anyone else is. Closing.
