### ISSUE TITLE
npm module

### ISSUE THREAD

**Issue by refractalize** [dwachss/bililiteRange#14]
Hi @dwachss, I have an NPM module for `jquery-sendkeys` maintained at [featurist/jquery-sendkeys](https://github.com/featurist/jquery-sendkeys). I'm very happy to add you as contributor, or to hand over the keys to the NPM module if you want to maintain it.

**Comment by dwachss** [comment]
I have virtually no experience with npm, so I would rather not take responsibility for it. Adding me as a contributor would be appreciated.Thank you. 

    On Tuesday, March 1, 2016 3:46 AM, Tim Macfarlane <notifications@github.com> wrote:
 

 Hi @dwachss, I have an NPM module for jquery-sendkeys maintained at featurist/jquery-sendkeys. I'm very happy to add you as contributor, or to hand over the keys to the NPM module if you want to maintain it. —

**Comment by dwachss** [comment]
closed
