### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by soumak77** [dwachss/bililiteRange#15]
@dwachss can you push a new release out to bower?  I see the last one was over 2 years ago and there have been many changes since then.

**Comment by dwachss** [comment]
I've not used bower (except that one time when I created the bower.json). Do I have to actually push anything, or just create a new release and update bower.json? I've done that.

**Comment by soumak77** [comment]
What you did is perfect.  ```bower install bililiteRange``` properly installs version 2.5.2.
