### ISSUE TITLE
Simulating typing at the 0th position of a content editable , simulates it in the previous text node instead 

### ISSUE THREAD

**Issue by hiteshdua1** [dwachss/bililiteRange#17]
Hi @dwachss ,

In simulate-key-sequence using bililiterange.js, when i select a all text within a single text element (including nbsp;) special character and starts typing, the typing starts from the previous text element 

This issue usually occurs when nbsp; is at the starting of the element i am about to start typing

**Comment by dwachss** [comment]
Interesting. Can you set up a demonstration of the problem? I'll try to look at it. 

    On Wednesday, June 21, 2017 7:35 AM, hiteshdua1 <notifications@github.com> wrote:
 

 Hi @dwachss ,In simulate-key-sequence using bililiterange.js, when i select a all text within a single text element (including nbsp;) special character and starts typing, the typing starts from the previous text elementThis issue usually occurs when nbsp; is at the starting of the element i am about to start typing—

**Comment by hiteshdua1** [comment]
Hi @dwachss ,

The fiddle is http://jsfiddle.net/xzoh82e3/4/

click before the ```&nbsp;``` and insert the text , the text is inserted before the p tag.

While analyzing the root cause, I believe issue points towards the method ```function w3cmoveBoundary (rng, n, bStart, el) ```.
The ```if (n <= length){``` was getting true for the previous node instead od the current one.

Please do check this.

**Comment by hiteshdua1** [comment]
Hi @dwachss  ,

Any update on this ? This is important for me.

**Comment by dwachss** [comment]
No, I haven't gotten to it. If you can solve it, send me a pull request.

**Comment by hiteshdua1** [comment]
Hi @dwachss ,

Issue can be replicated in the following fiddle : http://jsfiddle.net/xzoh82e3/4/

I have investigated the issue , please find the description below

Issue description :
When the typing is done at the beginning of 2nd <p> element tag, i.e before nbsp; character, the text node is inserted before the <p> element tag instead 

So let's say our DOM is this
```
<div id="textInput" contenteditable="true">
  <p>this is first p block</p>
  <p>&nbsp;aaaaa</p>
</div>
```

So for typing inside the <p> element , my text node should be inserted at beginning of <p> element tag before nbsp;


But the typing happens before the <p> element i.e 
instead what we get is the following DOM (please note the inserted text is "foobar"
```
<div id="textInput" contenteditable="true">
<p>this is first p block</p>
foobar<p>&nbsp;aaaaa</p>
</div>
```

The issue is in billiliteRange computation for range Bounds


```
function w3cstart(rng, constraint){
	if (rng.compareBoundaryPoints (START_TO_START, constraint) <= 0) return 0; // at or before the beginning
	if (rng.compareBoundaryPoints (END_TO_START, constraint) >= 0) return constraint.toString().length;
	rng = rng.cloneRange(); // don't change the original
	rng.setEnd (constraint.endContainer, constraint.endOffset); // they now end at the same place
	return constraint.toString().replace(/\r/g, '').length - rng.toString().replace(/\r/g, '').length;
}
function w3cend (rng, constraint){
	if (rng.compareBoundaryPoints (END_TO_END, constraint) >= 0) return constraint.toString().length; // at or after the end
	if (rng.compareBoundaryPoints (START_TO_END, constraint) <= 0) return 0;
	rng = rng.cloneRange(); // don't change the original
	rng.setStart (constraint.startContainer, constraint.startOffset); // they now start at the same place
	return rng.toString().replace(/\r/g, '').length;
}
```

The condition 

```
	return constraint.toString().replace(/\r/g, '').length - rng.toString().replace(/\r/g, '').length;
```

*Returns the same value when the caret is at the end of a text node or the beginning of the next text node.
This is because it is computing the value based the text.*

The following returns the total text content of the whole container in which typing is being performed

```
	constraint.toString().replace(/\r/g, '').length
```

Whereas , the following returns the text content based on the current caret position

```
 rng.toString().replace(/\r/g, '').length;
```

*Hence subtracting both, gives the same value when the text is at the end of the current text node or at the beginning of the next text node.*

Which leads to the following condition being true while selecting the text node for insertion in the following method

```
function w3cmoveBoundary (rng, n, bStart, el){
	// move the boundary (bStart == true ? start : end) n characters forward, up to the end of element el. Forward only!
	// if the start is moved after the end, then an exception is raised
	if (n <= 0) return;
	var node = rng[bStart ? 'startContainer' : 'endContainer'];
	if (node.nodeType == 3){
	  // we may be starting somewhere into the text
	  n += rng[bStart ? 'startOffset' : 'endOffset'];
	}
	while (node){
		if (node.nodeType == 3){
			var length = node.nodeValue.length;
			if (n <= length){
				rng[bStart ? 'setStart' : 'setEnd'](node, n);
				// special case: if we end next to a <br>, include that node.
				if (n == length){
					// skip past zero-length text nodes
					for (var next = nextnode (node, el); next && next.nodeType==3 && next.nodeValue.length == 0; next = nextnode(next, el)){
						rng[bStart ? 'setStartAfter' : 'setEndAfter'](next);
					}
					if (next && next.nodeType == 1 && next.nodeName == "BR") rng[bStart ? 'setStartAfter' : 'setEndAfter'](next);
				}
				return;
			}else{
				rng[bStart ? 'setStartAfter' : 'setEndAfter'](node); // skip past this one
				n -= length; // and eat these characters
			}
		}
		node = nextnode (node, el);
	}
}
```

The method which satisfies the following condition is that the node before the <p> element i.e the last caret of previous node instead of the 0th caret of the current node in which text was being typed.

```
if (n <= length){
```

*Hence the typing is being performed on the previous text node instead of the current text node.*

**Comment by dwachss** [comment]
This looks like a hard problem. As you've found, the issue is not the nbsp; it's the fact that the code works with text positions and there's no difference between the beginning of one element and the end of the previous one. 
I'll have to look at that. It may not be solvable :( If you have ideas, please let me know.

**Comment by hiteshdua1** [comment]
Hi @dwachss ,

I was thinking in terms of using the `window.getSelection()`  Api Here. We could use the anchorNode to validate , if the text node we are typing is the correct text node or not 

eg 
We could add a check in the following method 
```function w3cmoveBoundary (rng, n, bStart, el){
	// move the boundary (bStart == true ? start : end) n characters forward, up to the end of element el. Forward only!
	// if the start is moved after the end, then an exception is raised
	if (n <= 0) return;
	var node = rng[bStart ? 'startContainer' : 'endContainer'];
	if (node.nodeType == 3){
	  // we may be starting somewhere into the text
	  n += rng[bStart ? 'startOffset' : 'endOffset'];
	}
	while (node){
		if (node.nodeType == 3){
			if (n <= node.nodeValue.length && isCorrectTextNode(node) ){

					rng[bStart ? 'setStart' : 'setEnd'](node, n);
					// special case: if we end next to a <br>, include that node.
					if (n == node.nodeValue.length){
						// skip past zero-length text nodes
						for (var next = nextnode (node, el); next && next.nodeType==3 && next.nodeValue.length == 0; next = nextnode(next, el)){
							rng[bStart ? 'setStartAfter' : 'setEndAfter'](next);
						}
						if (next && next.nodeType == 1 && next.nodeName == "BR") rng[bStart ? 'setStartAfter' : 'setEndAfter'](next);
					}
					return;
			}else{
				rng[bStart ? 'setStartAfter' : 'setEndAfter'](node); // skip past this one
				n -= node.nodeValue.length; // and eat these characters
			}
		}
		node = nextnode (node, el);
	}
}
```
Here, as you can see , we can add a check 
``` isCorrectTextNode(node)``` 

which validates this boundry condition using `window.getSelection(0` api

the method would do the following computation

```
function isCorrectTextNode(node) {

	var selection = window.getSelection();
	var currentNode = selection.anchorNode;

	// Only check in case of Boundry conditions i.e when the caret is at position 0 
	if (selection.anchorOffset === 0) {
		if (currentNode.nodeType !== 3) {
			// Getting the text node
			currentNode = currentNode.childNodes[0];

			// This is a safe check 
			// we are returning true if child node is not a text node, continue with what you were already doing
			if (currentNode.nodeType !== 3) {
				return true;
			}
		}

		// Current Node matched, return True
		if (currentNode === node) {
			return true;
		}

		// Node does not match, return false
		return false;
	}

	return true;
}
```

Which basically checks the text node based on current caret position.

This is a bugfix I came up with, you could suggest if anything else comes to your mind for the same,

**Comment by dwachss** [comment]
The problem is that ranges are not inherently connected to the selection. That's your use case but it doesn't generalize.

**Comment by dwachss** [comment]
I don't see a solution with bililiteRange's underlying structure: ranges only know about character positions. If you think of an elegant solution, please re-open this.
