### ISSUE TITLE
Simulating typing between 2 break tags of a content editable , simulates after the next br tag

### ISSUE THREAD

**Issue by hiteshdua1** [dwachss/bililiteRange#21]
Hi @dwachss ,

I recently encountered an issue with br tag

Issue was due to 
The handling of
`                    // special case: if we end next to a <br>, include that node. `

The following condition creates an issue when the typing is being performed between 2 br tags

```
function w3cmoveBoundary (rng, n, bStart, el){
	// move the boundary (bStart == true ? start : end) n characters forward, up to the end of element el. Forward only!
	// if the start is moved after the end, then an exception is raised
	if (n <= 0) return;
	var node = rng[bStart ? 'startContainer' : 'endContainer'];
	if (node.nodeType == 3){
	  // we may be starting somewhere into the text
	  n += rng[bStart ? 'startOffset' : 'endOffset'];
	}
	while (node){
		if (node.nodeType == 3){
			var length = node.nodeValue.length;
			if (n <= length){
				rng[bStart ? 'setStart' : 'setEnd'](node, n);
				// special case: if we end next to a <br>, include that node.
				if (n == length){
					// skip past zero-length text nodes
					for (var next = nextnode (node, el); next && next.nodeType==3 && next.nodeValue.length == 0; next = nextnode(next, el)){
						rng[bStart ? 'setStartAfter' : 'setEndAfter'](next);
					}
					if (next && next.nodeType == 1 && next.nodeName == "BR") rng[bStart ? 'setStartAfter' : 'setEndAfter'](next);
				}
				return;
			}else{
				rng[bStart ? 'setStartAfter' : 'setEndAfter'](node); // skip past this one
				n -= length; // and eat these characters
			}
		}
		node = nextnode (node, el);
	}
}
```

Eg 
If i simulate text between 2 br tags , the first character is typed after the 1st br tag and then the caret moves forward, the second character after typing should be inserted after the first character, but instead the caret encounters another br tag after it and hence simulates the text after that br tag, hence in the next line.

![br_tag_issue](https://user-images.githubusercontent.com/1966349/30027691-a6bfa368-919f-11e7-9f85-0c6f224b0697.png)

**Comment by dwachss** [comment]
It's a similar problem to the one you had before: bililiteRange uses character positions so elements that contain no characters but alter text layout cause problems. 
The solution I've used (and seen elsewhere) is hacky but works: intercept the typing or insertion of <br>s etc. and insert a '\n' beforehand.

**Comment by dwachss** [comment]
I don't see a solution with bililiteRange's underlying structure: ranges only know about character positions. If you think of an elegant solution, please re-open this.
