### ISSUE TITLE
``{selectall}`` doesn't work with jQuery plugin

### ISSUE THREAD

**Issue by JohnMcLear** [dwachss/bililiteRange#33]
Discovered here: https://github.com/ether/etherpad-lite/pull/4623/files

```
    // get the first text element out of the inner iframe
    const $firstTextElement = inner$('div').find('span').first(); // also tried div..
    console.log($firstTextElement); // correct...
    // select this text element
    $firstTextElement.sendkeys('{selectall}');
```

``delete`` works, ``tab`` works, ``enter`` doesn't at start of line.  ``selection`` and ``rightarrow`` also don't work.  

Nothing happens with ``selectall`` which means the syntax is correct in the test.

``rng.lengt`` has the correct value (20 in this case).

I haven't dived any deeper as of yet.  I imagine it's something to do with focus and select / caret events but IDK :\

**Comment by dwachss** [comment]
My quick test with the kavanot editor (kavanot.name/foo/edit) shows no problems. I will try to look at it.

**Comment by JohnMcLear** [comment]
Thanks.  Feel free to bump me when you are looking at it and I can talk you through getting setup if you get stuck.

**Comment by JohnMcLear** [comment]
Just FYI I did a workaround that does a jQuery trigger event which is working fine but obv I'd like to use sendkeys as it's our chosen method for interacting with the editor 👍

**Comment by dwachss** [comment]
Closed; can't reproduce.
