### ISSUE TITLE
bililiteRange.util.js `line(n)` docs contradict implementation

### ISSUE THREAD

**Issue by idupree** [dwachss/bililiteRange#7]
http://bililite.com/blog/2013/02/08/bililiterange-plugins/ says "line(n): Set the range to the entire line n", while the implementation only sets the range to be at the beginning of the line.

I can get the docs' behavior (aside from line(0) and line(past-the-end)) from `line(n).bounds('line')`.  I could get the current behavior from the documented behavior by `line(n).bounds ('startbounds')`.  I think I like the documented behavior better than the current behavior, though I don't feel strongly about it.

**Comment by dwachss** [comment]
you are correct; thanks for noticing that. I will update the documentation to reflect the actual behavior. 


     On Wednesday, November 11, 2015 1:40 PM, Isaac Vivian Dupree <notifications@github.com> wrote:
   

 http://bililite.com/blog/2013/02/08/bililiterange-plugins/ says "line(n): Set the range to the entire line n", while the implementation only sets the range to be at the beginning of the line.I can get the docs' behavior (aside from line(0) and line(past-the-end)) from line(n).bounds('line'). I could get the current behavior from the documented behavior by line(n).bounds ('startbounds'). I think I like the documented behavior better than the current behavior, though I don't feel strongly about it.—

**Comment by idupree** [comment]
Thanks!
