### ISSUE TITLE
Uncaught ReferenceError: simplechar is not defined

### ISSUE THREAD

**Issue by old-woman** [dwachss/bililiteRange#9]
Error: Uncaught ReferenceError: simplechar is not defined
File: bililiteRange.js
Line: 327

I would like to say: I love you!!! man!!!!! You saved my a lot of time!  When I use your code before, I want to kill myself because I was stuck on a hard problem. The problem bother me much days.

If I meet you, I want to kiss you!  LOL!!

Thanks!!!

**Comment by dwachss** [comment]
Good catch. It should have been fixed as of commit 806a557:
https://github.com/dwachss/bililiteRange/commit/806a557f45e0aab50962219ce538c574adb26f22

Thanks for the positive feedback!
